version: "3.9"

services:
  minilisp-scratchpad:
    image: ${IMG_DEV}
    command: ${SCRATCHPAD_DEV_CMD}
    ports:
      - ${SCRATCHPAD_PORT}:${SCRATCHPAD_PORT}

  minilisp-http:
    image: ${IMG_DEV}
    ports:
      - ${LISP_HTTP_PORT}:${LISP_HTTP_PORT}
