version: "3.9"

services:

  minilisp-scratchpad:
    image: ${IMG}
    container_name: ${SCRATCHPADER}
    ports:
      - ${SCRATCHPAD_PORT}:${SCRATCHPAD_PORT}
    command: serve -s -l ${SCRATCHPAD_PORT} 4-scratchpad/dist

  minilisp-http:
    image: ${IMG}
    container_name: ${LISP_HTTPER}
    ports:
      - ${LISP_HTTP_PORT}:${LISP_HTTP_PORT}
    command: runhaskell 3-HTTP/HTTP.hs
