version: "3.9"

services:

  minilisp-scratchpad:
    image: ${IMG}
    container_name: ${SCRATCHPADER}
    command: ${SCRATCHPAD_CMD}
    networks:
      - minilisp-net

  minilisp-http:
    image: ${IMG}
    container_name: ${LISP_HTTPER}
    ports:
      - ${LISP_HTTP_PORT}:${LISP_HTTP_PORT}
    command: ${LISP_HTTP_CMD}
    networks:
      - minilisp-net

networks:
  minilisp-net:
    name: minilisp-net
    driver: bridge
